defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    date_fmt: "%F"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    categories: "news"
    date_fmt: "%F"

exclude:
- README.md
- Gemfile
- Gemfile.lock

name: JACK Audio Connection Kit
markdown: Kramdown
highlighter: rouge

url: "https://jackaudio.org"

organization:
  url: "https://github.com/jackaudio"

repository:
  branch: "master"
  url: "https://github.com/jackaudio/jackaudio.github.com"
